### ISSUE TITLE
Correção de scrip de geração equipe 6

### ISSUE THREAD

**Issue by wandressareis** [ed-henrique/analise-de-algoritmos#2]
O script está gerando os arquivos .txt, porém os valores numéricos dos intervalos definidos não estão sendo gerados.

**Comment by ed-henrique** [comment]
Por favor, verifique se o ambiente possui os comandos `shuf` e `sort`, pois eles são essenciais para o funcionamento do programa.

**Comment by ed-henrique** [comment]
O problema foi resolvido?

Fui informado por um dos integrantes da equipe de vocês que o sistema utilizado é Ubuntu via WSL. Talvez haja alguma limitação por causa disso.

Recomendo instalar as dependências do script (esqueci de especificar no README) via o comando abaixo:

```bash
sudo apt-get update && sudo apt-get install textutils coreutils
```

Após a instalação, utilize esses comandos para garantir que tanto o `shuf` quanto o `sort` estão funcionando.

```bash
shuf --version
```

```bash
sort --version
```

Se tudo estiver funcional, peço que feche esta issue.
